import type {
  SkillApproval,
  SkillCategory,
  SkillField,
  SkillMemory,
} from "@unioffice/core";

/**
 * The product's own skills.
 *
 * Data, not behaviour: each entry is the same shape an organization writes,
 * and nothing in the product branches on a particular slug. Required tools
 * and capabilities use only what exists - the three local tools and the
 * capability vocabulary the seeded workforce holds - so a system skill never
 * promises something no agent can do. Nothing here reaches the internet; a
 * research skill works over supplied sources and company knowledge.
 */

export interface SystemSkillDefinition {
  slug: string;
  name: string;
  description: string;
  category: SkillCategory;
  version: number;
  instructions: string;
  inputs: SkillField[];
  outputs: SkillField[];
  requiredTools: string[];
  requiredCapabilities: string[];
  approval: SkillApproval;
  memory: SkillMemory;
}

const text = (name: string, description: string, required = true): SkillField => ({ name, type: "text", description, required });
const list = (name: string, description: string, required = true): SkillField => ({ name, type: "list", description, required });
const table = (name: string, description: string, required = true): SkillField => ({ name, type: "table", description, required });

export const SYSTEM_SKILLS: readonly SystemSkillDefinition[] = [
  // Engineering ---------------------------------------------------------------
  {
    slug: "code-review",
    name: "Code review",
    description: "Review a change for correctness, security, readability and missing tests.",
    category: "engineering",
    version: 1,
    instructions: [
      "Read the change and the stated intent before judging it.",
      "Check correctness first: edge cases, error handling, concurrency and data loss.",
      "Then security: input validation, authorization, secrets and injection.",
      "Then maintainability: naming, duplication and whether tests cover the change.",
      "Report each finding with where it is, why it matters and a concrete fix. Say plainly when you found nothing serious.",
    ].join("\n"),
    inputs: [text("change", "The diff or code under review."), text("intent", "What the change is meant to do.", false)],
    outputs: [list("findings", "Each problem, its location, severity and fix."), text("verdict", "Ready, ready with changes, or not ready.")],
    requiredTools: [],
    requiredCapabilities: ["coding"],
    approval: "none",
    memory: "recall",
  },
  {
    slug: "debugging",
    name: "Debugging",
    description: "Find the most likely cause of a defect from symptoms, logs and code, and propose a fix.",
    category: "engineering",
    version: 1,
    instructions: [
      "Restate the observed behaviour and the expected behaviour.",
      "List the plausible causes, then rule them in or out using the evidence supplied. Do not invent evidence.",
      "Name the most likely cause and how to confirm it.",
      "Propose the smallest fix and how to verify it did not break anything else.",
    ].join("\n"),
    inputs: [text("symptoms", "What is going wrong and when."), text("evidence", "Logs, errors, code or reproduction steps.", false)],
    outputs: [text("likely_cause", "The most likely cause and why."), list("checks", "How to confirm it."), text("fix", "The proposed fix.")],
    requiredTools: [],
    requiredCapabilities: ["coding"],
    approval: "none",
    memory: "recall",
  },
  {
    slug: "api-design",
    name: "API design",
    description: "Design or review an API: resources, operations, errors, authorization and versioning.",
    category: "engineering",
    version: 1,
    instructions: [
      "Start from the callers and what they need to do, not from the storage.",
      "Define resources, operations, request and response shapes, and error cases.",
      "State who may call each operation and what is checked on the server.",
      "Call out pagination, idempotency and how the API can change without breaking callers.",
    ].join("\n"),
    inputs: [text("requirements", "What the API must let callers do."), text("constraints", "Existing systems, conventions or limits.", false)],
    outputs: [table("operations", "Each operation with inputs, outputs, errors and authorization."), list("decisions", "Design decisions and their trade-offs.")],
    requiredTools: [],
    requiredCapabilities: ["technical_design"],
    approval: "none",
    memory: "recall",
  },
  {
    slug: "database-investigation",
    name: "Database investigation",
    description: "Investigate a data question or slow query from schema, plans and samples supplied.",
    category: "engineering",
    version: 1,
    instructions: [
      "Work only from the schema, queries, plans and data supplied - you cannot connect to a database.",
      "Explain what the data or plan shows, and what it does not.",
      "Recommend indexes, query changes or data fixes, each with its risk.",
      "Never recommend a destructive change without saying how to back it out.",
    ].join("\n"),
    inputs: [text("question", "What needs to be found out or fixed."), text("material", "Schema, query, plan or sample rows.")],
    outputs: [text("findings", "What the material shows."), list("recommendations", "Changes with their risk and rollback.")],
    requiredTools: [],
    requiredCapabilities: ["technical_design"],
    approval: "none",
    memory: "recall",
  },
  {
    slug: "test-generation",
    name: "Test generation",
    description: "Propose tests that pin down the behaviour of a piece of code, including failure cases.",
    category: "engineering",
    version: 1,
    instructions: [
      "Identify the behaviour that matters to callers, including failures and boundaries.",
      "Write test cases as behaviour, one idea per test, with clear names.",
      "Prefer tests that would fail if the behaviour broke over tests of implementation details.",
    ].join("\n"),
    inputs: [text("code", "The code or behaviour to test."), text("framework", "The test framework in use.", false)],
    outputs: [list("cases", "Each test: name, setup, action, expected result."), text("gaps", "What still cannot be tested and why.", false)],
    requiredTools: [],
    requiredCapabilities: ["coding"],
    approval: "none",
    memory: "none",
  },
  {
    slug: "incident-analysis",
    name: "Incident analysis",
    description: "Reconstruct what happened in an incident, its impact and causes, and what to change.",
    category: "engineering",
    version: 1,
    instructions: [
      "Build a timeline from the evidence supplied, marking what is known and what is inferred.",
      "Separate the trigger from the contributing causes.",
      "State the impact in terms of customers and the business.",
      "Recommend changes that address causes, not people. Each has an owner role and a way to tell it worked.",
    ].join("\n"),
    inputs: [text("evidence", "Alerts, logs, messages and notes from the incident.")],
    outputs: [table("timeline", "What happened when, and how it is known."), text("causes", "Trigger and contributing causes."), list("actions", "Follow-up changes with owner role.")],
    requiredTools: ["datetime"],
    requiredCapabilities: ["technical_design"],
    approval: "none",
    memory: "recall",
  },

  // Research ------------------------------------------------------------------
  {
    slug: "web-research",
    name: "Source research",
    description: "Answer a question from supplied sources and company knowledge, citing each claim.",
    category: "research",
    version: 1,
    instructions: [
      "You cannot browse the internet. Work from the sources supplied in the task and from recalled company knowledge.",
      "Cite the source behind every claim. Say plainly when the sources do not answer the question.",
      "Separate what the sources say from your own inference.",
    ].join("\n"),
    inputs: [text("question", "What needs to be answered."), text("sources", "Material to work from.", false)],
    outputs: [text("answer", "The answer with citations."), list("open_questions", "What the sources leave unanswered.")],
    requiredTools: [],
    requiredCapabilities: ["research"],
    approval: "none",
    memory: "recall",
  },
  {
    slug: "competitor-analysis",
    name: "Competitor analysis",
    description: "Compare competitors on positioning, offer, pricing and weaknesses from supplied material.",
    category: "research",
    version: 1,
    instructions: [
      "Compare on the dimensions the task names; otherwise positioning, offer, pricing, customers and weaknesses.",
      "Mark each comparison with its source and how current it is.",
      "End with what it means for the company - where to compete and where not to.",
    ].join("\n"),
    inputs: [text("competitors", "Who to compare."), text("material", "What is known about them.", false)],
    outputs: [table("comparison", "Competitors against each dimension."), list("implications", "What the company should do about it.")],
    requiredTools: [],
    requiredCapabilities: ["research"],
    approval: "none",
    memory: "recall",
  },
  {
    slug: "market-research",
    name: "Market research",
    description: "Size and describe a market or customer segment from supplied data, stating assumptions.",
    category: "research",
    version: 1,
    instructions: [
      "State the question and the segment precisely before estimating anything.",
      "Show every estimate as a calculation from stated assumptions, using the calculator for arithmetic.",
      "Give a range rather than a single figure when the inputs are uncertain.",
    ].join("\n"),
    inputs: [text("question", "The market question."), text("data", "Figures and sources available.", false)],
    outputs: [text("estimate", "The estimate or range and how it was reached."), list("assumptions", "Each assumption and how sensitive the result is to it.")],
    requiredTools: ["calculator"],
    requiredCapabilities: ["research"],
    approval: "none",
    memory: "recall",
  },
  {
    slug: "source-synthesis",
    name: "Source synthesis",
    description: "Combine several sources into one account, noting agreement and contradiction.",
    category: "research",
    version: 1,
    instructions: [
      "Read every source before writing.",
      "Group what they say by theme; note where they agree, disagree or are silent.",
      "Attribute each point to its sources. Never smooth over a contradiction.",
    ].join("\n"),
    inputs: [list("sources", "The material to combine.")],
    outputs: [text("synthesis", "The combined account with attribution."), list("contradictions", "Where sources disagree.")],
    requiredTools: [],
    requiredCapabilities: ["synthesis"],
    approval: "none",
    memory: "recall",
  },
  {
    slug: "briefing-generation",
    name: "Research briefing",
    description: "Turn research into a short briefing a decision-maker can act on.",
    category: "research",
    version: 1,
    instructions: [
      "Lead with the conclusion and the decision it informs.",
      "Give only the evidence needed to trust the conclusion, with sources.",
      "Close with risks, unknowns and the recommended next step.",
    ].join("\n"),
    inputs: [text("research", "The findings to brief on."), text("audience", "Who the briefing is for.", false)],
    outputs: [text("briefing", "The briefing, one page or less.")],
    requiredTools: [],
    requiredCapabilities: ["writing"],
    approval: "none",
    memory: "recall",
  },

  // Finance -------------------------------------------------------------------
  {
    slug: "financial-analysis",
    name: "Financial analysis",
    description: "Analyse financial figures: trends, ratios, unusual items and what they mean.",
    category: "finance",
    version: 1,
    instructions: [
      "Use the calculator for every figure you derive. Never compute in your head.",
      "Show the inputs behind each figure so it can be checked.",
      "Flag unusual items with why they are unusual and what would explain them.",
      "Separate what the numbers show from what you infer.",
    ].join("\n"),
    inputs: [table("figures", "The financial data to analyse."), text("question", "What the analysis must answer.")],
    outputs: [table("metrics", "Derived figures with their inputs."), list("unusual_items", "Anomalies and possible explanations."), text("conclusion", "What it means.")],
    requiredTools: ["calculator"],
    requiredCapabilities: ["financial_analysis"],
    approval: "none",
    memory: "recall",
  },
  {
    slug: "budget-review",
    name: "Budget review",
    description: "Review a budget for completeness, realism and risk.",
    category: "finance",
    version: 1,
    instructions: [
      "Check totals and subtotals with the calculator.",
      "Question each large or fast-growing line: what drives it and is the assumption realistic.",
      "List what is missing that a budget like this usually needs.",
    ].join("\n"),
    inputs: [table("budget", "The budget lines."), text("context", "What the budget is for.", false)],
    outputs: [list("issues", "Errors, weak assumptions and gaps."), text("assessment", "Overall realism and main risks.")],
    requiredTools: ["calculator"],
    requiredCapabilities: ["financial_analysis"],
    approval: "none",
    memory: "recall",
  },
  {
    slug: "variance-analysis",
    name: "Variance analysis",
    description: "Explain the differences between actuals and plan, line by line.",
    category: "finance",
    version: 1,
    instructions: [
      "Compute each variance in amount and percentage with the calculator.",
      "Explain the material variances; ignore immaterial ones and say which threshold you used.",
      "Separate one-off effects from trends.",
    ].join("\n"),
    inputs: [table("actuals", "Actual figures."), table("plan", "Planned figures.")],
    outputs: [table("variances", "Each line: plan, actual, variance, explanation.")],
    requiredTools: ["calculator"],
    requiredCapabilities: ["financial_analysis"],
    approval: "none",
    memory: "recall",
  },
  {
    slug: "forecasting",
    name: "Forecasting",
    description: "Project figures forward from history and stated assumptions, period by period.",
    category: "finance",
    version: 1,
    instructions: [
      "State the method and every assumption before producing numbers.",
      "Use the calculator for every period and the date tool for period boundaries.",
      "Give a base case and, where uncertainty is material, a low and high case.",
    ].join("\n"),
    inputs: [table("history", "Past figures."), text("assumptions", "Growth, seasonality or other drivers.", false)],
    outputs: [table("forecast", "Each period with its figure and case."), list("assumptions", "What the forecast depends on.")],
    requiredTools: ["calculator", "datetime"],
    requiredCapabilities: ["calculation"],
    approval: "none",
    memory: "recall",
  },

  // People --------------------------------------------------------------------
  {
    slug: "candidate-screening",
    name: "Candidate screening",
    description: "Assess candidates against a role's stated requirements, consistently and fairly.",
    category: "people",
    version: 1,
    instructions: [
      "Assess only against the requirements stated for the role.",
      "Never use or infer age, gender, ethnicity, religion, disability, family status or other protected characteristics.",
      "Give evidence from the application for each assessment, and say where evidence is missing.",
      "This is a recommendation for a person to review, not a decision.",
    ].join("\n"),
    inputs: [text("role", "The role and its requirements."), list("candidates", "Applications to assess.")],
    outputs: [table("assessments", "Each candidate against each requirement, with evidence."), text("recommendation", "Who to interview, for a person to decide.")],
    requiredTools: [],
    requiredCapabilities: ["people_operations"],
    approval: "required",
    memory: "none",
  },
  {
    slug: "onboarding-planning",
    name: "Onboarding planning",
    description: "Plan a new person's first weeks: access, introductions, learning and early goals.",
    category: "people",
    version: 1,
    instructions: [
      "Organise the plan by week, with day-one essentials first.",
      "Cover access and equipment, people to meet, what to learn and a first meaningful goal.",
      "Name an owner role for each item.",
    ].join("\n"),
    inputs: [text("role", "The role being onboarded."), text("start_date", "When they start.", false)],
    outputs: [table("plan", "Week, item, owner role.")],
    requiredTools: ["datetime"],
    requiredCapabilities: ["people_operations"],
    approval: "none",
    memory: "recall",
  },
  {
    slug: "policy-drafting",
    name: "Policy drafting",
    description: "Draft an internal policy that is clear, enforceable and consistent with existing ones.",
    category: "people",
    version: 1,
    instructions: [
      "State the policy's purpose and who it applies to first.",
      "Write rules people can follow without interpretation; avoid vague terms.",
      "Check against recalled company policies and flag conflicts.",
      "This is a draft for people to review and adopt.",
    ].join("\n"),
    inputs: [text("topic", "What the policy covers."), text("requirements", "Constraints it must meet.", false)],
    outputs: [text("draft", "The policy text."), list("open_points", "Decisions left for people.")],
    requiredTools: [],
    requiredCapabilities: ["process_design"],
    approval: "none",
    memory: "recall",
  },
  {
    slug: "employee-communication",
    name: "Employee communication",
    description: "Write a message to employees that is clear, honest and considerate.",
    category: "people",
    version: 1,
    instructions: [
      "Say what is happening, why, what it means for the reader and what they should do.",
      "Use plain language. Do not spin bad news.",
      "Keep it as short as it can be while answering the obvious questions.",
    ].join("\n"),
    inputs: [text("news", "What needs to be communicated."), text("audience", "Who is receiving it.")],
    outputs: [text("message", "The message, ready to review.")],
    requiredTools: [],
    requiredCapabilities: ["writing"],
    approval: "none",
    memory: "recall",
  },

  // Communication -------------------------------------------------------------
  {
    slug: "executive-briefing",
    name: "Executive briefing",
    description: "Brief an executive on a situation: the point, the evidence, the ask.",
    category: "communication",
    version: 1,
    instructions: [
      "Open with the single most important point and any decision needed.",
      "Support it with the few facts that matter. Link or name sources.",
      "Close with options, a recommendation and what happens by when.",
    ].join("\n"),
    inputs: [text("situation", "What the executive needs to know.")],
    outputs: [text("briefing", "The briefing, under 300 words.")],
    requiredTools: [],
    requiredCapabilities: ["communication"],
    approval: "none",
    memory: "recall",
  },
  {
    slug: "stakeholder-update",
    name: "Stakeholder update",
    description: "Update stakeholders on progress, risks and what is needed from them.",
    category: "communication",
    version: 1,
    instructions: [
      "Status first: on track, at risk or off track, and why.",
      "Then progress since the last update, upcoming milestones with dates, and risks.",
      "End with exactly what is needed from the reader, if anything.",
    ].join("\n"),
    inputs: [text("progress", "What has happened."), text("audience", "Who the stakeholders are.", false)],
    outputs: [text("update", "The update.")],
    requiredTools: ["datetime"],
    requiredCapabilities: ["stakeholder_messaging"],
    approval: "none",
    memory: "recall",
  },
  {
    slug: "meeting-summary",
    name: "Meeting summary",
    description: "Summarise a meeting into decisions, actions and open questions.",
    category: "communication",
    version: 1,
    instructions: [
      "Record decisions exactly as agreed, not as discussed.",
      "List each action with an owner and due date where the notes give them; say so where they do not.",
      "Keep discussion detail only where it explains a decision.",
    ].join("\n"),
    inputs: [text("notes", "Transcript or notes from the meeting.")],
    outputs: [list("decisions", "What was decided."), table("actions", "Action, owner, due date."), list("open_questions", "What was left unresolved.")],
    requiredTools: [],
    requiredCapabilities: ["writing"],
    approval: "none",
    memory: "none",
  },
  {
    slug: "announcement-drafting",
    name: "Announcement drafting",
    description: "Draft an announcement for customers, partners or the public.",
    category: "communication",
    version: 1,
    instructions: [
      "Lead with what changes for the reader.",
      "Keep claims factual and supportable; never overstate.",
      "This is a draft: anything that will be published externally is reviewed by a person first.",
    ].join("\n"),
    inputs: [text("news", "What is being announced."), text("audience", "Who it is for.")],
    outputs: [text("announcement", "The draft."), list("claims_to_verify", "Statements a person should check before publishing.")],
    requiredTools: [],
    requiredCapabilities: ["communication"],
    approval: "required",
    memory: "recall",
  },
];
